<script setup lang="ts">
import { 
  LayoutGrid,
  FlaskConical, 
  Cpu, 
  Wrench, 
  Palette, 
  Sigma,
  Atom,
  Microscope,
  Brain,
  Globe,
  Star,
  Leaf,
  Github,
  ExternalLink,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  Menu,
  X,
  Search,
  BookOpen,
  Video,
  Calculator,
  Code,
  Code2,
  GraduationCap,
  Trophy,
  Medal,
  Database,
  Cog,
  Zap,
  Building2,
  Building,
  Rocket,
  HeartPulse,
  Factory,
  Gem,
  Shield,
  BarChart3,
  Smartphone,
  Cloud,
  Settings,
  Gamepad2,
  Link,
  Monitor,
  Landmark,
  Music,
  Drama,
  Film,
  Camera,
  PenTool,
  Shirt,
  Variable,
  TrendingUp,
  Grid3X3,
  PieChart,
  Binary,
  Hash,
  Hexagon,
  Waves,
  BrainCircuit,
  Telescope,
  Dna,
  Mountain,
  Trees,
  Puzzle,
  Package,
  Cat,
  Coffee,
  Box,
  Eye,
  Network,
  Flame,
  Target,
  Laptop,
  Lock,
  Check,
  Dice5,
  AlertTriangle,
  Sprout,
  Wind,
  Apple,
  CircleCheck,
  Scroll,
  Pencil,
  Ruler,
  Home,
  Type,
  Layout,
  Scissors,
  Pin,
  FileText,
  Clapperboard,
  Newspaper,
  Piano,
  Sliders,
  SlidersHorizontal,
  Tent,
  PersonStanding,
  Lightbulb,
  FileCode,
  Hammer,
  Beaker,
  RefreshCw,
  Save,
  Recycle,
  Flag,
  Droplets,
  Thermometer,
  Car,
  Plane,
  Truck,
  Radio,
  Mic,
  Bone,
  Circle,
  Square,
  Triangle,
  CircleDot,
  ClipboardList,
  CloudCog,
  Container,
  Server,
  Plug,
  Mail,
  MessageCircle,
  Smile,
  Sparkles,
  Heart,
  School,
  DollarSign,
  FileEdit,
  Paintbrush,
  Bot,
  User,
  Loader,
  Satellite,
  Snowflake,
  type LucideIcon
} from 'lucide-vue-next'

interface Props {
  name: string
  size?: number | string
  class?: string
  strokeWidth?: number
}

const props = withDefaults(defineProps<Props>(), {
  size: 24,
  strokeWidth: 2
})

const icons = {
  // Science
  flask: FlaskConical,
  atom: Atom,
  microscope: Microscope,
  dna: Dna,
  globe: Globe,
  telescope: Telescope,
  brain: Brain,
  leaf: Leaf,
  trees: Trees,
  mountain: Mountain,
  star: Star,
  
  // Technology
  cpu: Cpu,
  code: Code,
  code2: Code2,
  shield: Shield,
  barchart: BarChart3,
  'bar-chart-3': BarChart3,
  globe2: Globe,
  smartphone: Smartphone,
  cloud: Cloud,
  settings: Settings,
  gamepad: Gamepad2,
  link: Link,
  database: Database,
  
  // Engineering
  cog: Cog,
  zap: Zap,
  building2: Building2,
  building: Building,
  rocket: Rocket,
  heartpulse: HeartPulse,
  factory: Factory,
  gem: Gem,
  wrench: Wrench,
  
  // Arts
  palette: Palette,
  monitor: Monitor,
  landmark: Landmark,
  music: Music,
  drama: Drama,
  film: Film,
  camera: Camera,
  pentool: PenTool,
  shirt: Shirt,
  
  // Mathematics
  sigma: Sigma,
  variable: Variable,
  trendingup: TrendingUp,
  grid3x3: Grid3X3,
  piechart: PieChart,
  binary: Binary,
  hash: Hash,
  hexagon: Hexagon,
  waves: Waves,
  braincircuit: BrainCircuit,
  calculator: Calculator,
  
  // General
  github: Github,
  external: ExternalLink,
  'arrow-right': ArrowRight,
  arrowRight: ArrowRight,
  'arrow-left': ArrowLeft,
  'chevron-down': ChevronDown,
  menu: Menu,
  close: X,
  search: Search,
  book: BookOpen,
  video: Video,
  graduation: GraduationCap,
  trophy: Trophy,
  medal: Medal,
  
  // Additional icons
  puzzle: Puzzle,
  package: Package,
  cat: Cat,
  coffee: Coffee,
  box: Box,
  eye: Eye,
  network: Network,
  flame: Flame,
  target: Target,
  laptop: Laptop,
  lock: Lock,
  check: Check,
  dice: Dice5,
  'alert-triangle': AlertTriangle,
  sprout: Sprout,
  flutter: Wind,
  
  // More icons
  apple: Apple,
  'check-circle': CircleCheck,
  scroll: Scroll,
  pencil: Pencil,
  ruler: Ruler,
  home: Home,
  type: Type,
  layout: Layout,
  scissors: Scissors,
  needle: Pin,
  'file-text': FileText,
  clapperboard: Clapperboard,
  newspaper: Newspaper,
  piano: Piano,
  sliders: Sliders,
  tent: Tent,
  'person-standing': PersonStanding,
  lightbulb: Lightbulb,
  'file-code': FileCode,
  hammer: Hammer,
  beaker: Beaker,
  'refresh-cw': RefreshCw,
  save: Save,
  recycle: Recycle,
  flag: Flag,
  droplets: Droplets,
  thermometer: Thermometer,
  car: Car,
  plane: Plane,
  truck: Truck,
  radio: Radio,
  mic: Mic,
  bone: Bone,
  circle: Circle,
  square: Square,
  triangle: Triangle,
  'circle-dot': CircleDot,
  'clipboard-list': ClipboardList,
  'cloud-cog': CloudCog,
  container: Container,
  server: Server,
  plug: Plug,
  mail: Mail,
  'message-circle': MessageCircle,
  smile: Smile,
  sparkles: Sparkles,
  heart: Heart,
  school: School,
  
  // Aliases for common naming variations
  grid: LayoutGrid,
  dices: Dice5,
  'flask-conical': FlaskConical,
  'grid-3x3': Grid3X3,
  'sliders-horizontal': SlidersHorizontal,
  dollarSign: DollarSign,
  'dollar-sign': DollarSign,
  barChart3: BarChart3,
  refresh: RefreshCw,
  'file-edit': FileEdit,
  paintbrush: Paintbrush,
  'music-2': Music,
  wind: Wind,
  'book-open': BookOpen,
  'book': BookOpen,
  'graduation-cap': GraduationCap,
  'graduation': GraduationCap,
  user: User,
  bot: Bot,
  loader: Loader,
  satellite: Satellite,
  'trending-up': TrendingUp,
  snowflake: Snowflake
}

const iconComponent = computed(() => {
  const iconName = props.name as keyof typeof icons
  return icons[iconName] || Globe
})

const normalizedSize = computed(() => {
  if (typeof props.size === 'number') return props.size
  if (typeof props.size === 'string') {
    const parsed = parseInt(props.size, 10)
    return isNaN(parsed) ? 24 : parsed
  }
  return 24
})
</script>

<template>
  <component
    :is="iconComponent"
    :size="normalizedSize"
    :stroke-width="strokeWidth"
    :class="class"
  />
</template>
